import { app, BrowserWindow, ipcMain, Menu, autoUpdater, dialog, session } from "electron";
import { exec } from "child_process";
import { shell } from "electron";
import axios from "axios";
import fs from 'fs';
import fsExtra from 'fs-extra';
import path from 'path'
import fsFunctionListener from "./functions/fsFunction";
import shellFunctionListener from "./functions/shellFunction";
import testFunctionListener from "./functions/testFunction";
import MenuBuilder from "./menu";
import Store from "electron-store"
import { Setting } from "./setting"
import dotenv from 'dotenv';
import open from 'open';
import express from 'express';
import git from 'simple-git';
import keytar from 'keytar';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow | null = null;
let loginWindow: BrowserWindow | null = null;

//#region eventListeners
// 各Functionをレンダラーから呼び出せるように
// 中でipcMain.onなどを行い、ここで実行
dotenv.config();
testFunctionListener();
shellFunctionListener();
fsFunctionListener();
//#endregion

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

type User = {
    login: string,
    id: number,
    node_id: string,
    avatar_url: string,
    gravatar_id: string,
    url: string,
    html_url: string,
    followers_url: string,
    following_url: string,
    gists_url: string,
    starred_url: string,
    subscriptions_url: string,
    organizations_url: string,
    repos_url: string,
    events_url: string,
    received_events_url: string,
    type: string,
    site_admin: boolean,
    name: string,
    company: string,
    blog: string,
    location: string,
    email: string,
    hireable: boolean,
    bio: string,
    twitter_username: string,
    public_repos: number,
    public_gists: number,
    followers: number,
    following: number,
    created_at: string,
    updated_at: string,
    access_token: string,
};

let userData: User | null = null;

const saveToken = async (token: string) => {
  try {
    await keytar.setPassword('markin', 'GitHub', token);
  } catch (err) {
    console.error('Error saving token: ', err);
  }
};

ipcMain.handle('open-account', async (event, arg) => {
  // 新しいウィンドウを作成してGitHubのOAuthページを開く

  const client_id = process.env.CLIENT_ID;
  const client_secret = process.env.CLIENT_SECRET;

  const githubUrl = 'https://github.com/login/oauth/authorize?';
  const authUrl = `${githubUrl}client_id=${client_id}&scope=user,repo`;
  open(authUrl);

  const app = express();

  let serverInstance = app.listen(49095);
  app.get('/account', async (req, res) => { // ここを修正しました
    const code = req.query.code;

    if (code) {
      await axios({
        method: 'post',
        url: `https://github.com/login/oauth/access_token?client_id=${client_id}&client_secret=${client_secret}&code=${code}`,
        headers: {
          accept: 'application/json'
        }
      }).then(async (response) => { // ここを修正しました
        const accessToken = response.data.access_token;
        await saveToken(accessToken);
        // Now you can use this access token to make API calls
        const getUserData = await axios.get('https://api.github.com/user', { // ここを修正しました
          headers: {
            Authorization: `token ${accessToken}`
          }
        });
        userData = getUserData.data;

        if (mainWindow) {
          mainWindow.webContents.send('set-user', userData);
        }

        serverInstance.close();
      }).catch((error) => {
        console.error(`Error: ${error}`);
      });
    } else {
      console.error('No code found in the URL');
    }

    res.send('You can close this window now.');
  });
});

ipcMain.handle('get-menu-data', async (event) => {
  const menu = Menu.getApplicationMenu();
  if (!menu) {
    return null;
  }

  const serializableData = menu.items.map(item => ({
    id: item.id,
    label: item.label,
    accelerator: item.accelerator || null,
    visible: item.visible,
    subitem: item.submenu ? item.submenu.items.map(subitem => ({
      id: subitem.id,
      label: subitem.label,
      accelerator: subitem.accelerator || null,
      visible: subitem.visible,
    })) : null,
  }));

  return serializableData;
});

ipcMain.handle('window-close', () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) window.close();
});

ipcMain.handle('window-maximize', () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) {
    if (window.isMaximized()) {
      window.unmaximize();
    } else {
      window.maximize();
    }
  }
});

ipcMain.handle('window-minimize', () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) window.minimize();
});

ipcMain.handle('log', () => {
  console.log("hello")
});

ipcMain.handle('open-settings', async () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) window.webContents.send('set-isSetting', true);
});

ipcMain.handle('get-setting', async (event) => {
  const setting = new Setting();
  return setting.config;
})

ipcMain.handle('save-setting', async (event, config) => {
  const store = new Store();
  store.delete("config");
  store.set("config", config);
})

let projectDataPath = path.join(__dirname, 'ProjectData');

function projectDataReset() {
  const projectDataPath = path.join(__dirname, 'ProjectData');
  if (!fs.existsSync(projectDataPath)) {
    fs.mkdirSync(projectDataPath, { recursive: true });
  }
}

projectDataReset();
const gitP = git(projectDataPath);

ipcMain.handle('init-repo', async (event, repo) => {
  try {
    // Check if .git directory exists
    const repoPath = path.join(projectDataPath, repo);
    if (fs.existsSync(path.join(repoPath, '.git'))) {
      // If it exists, delete or rename it
      fs.rmdirSync(path.join(repoPath, '.git'), { recursive: true });
    }

    const gitP = git(repoPath);
    await gitP.init();

    // Check if 'origin' remote exists
    const remotes = await gitP.getRemotes();
    if (remotes.some(remote => remote.name === 'origin')) {
      // If it exists, remove it
      await gitP.removeRemote('origin');
    }
  } catch (err) {
    console.error('Error initializing and pushing repo: ', err);
  }
});

ipcMain.handle('clone-repo', async (event, repo, url) => {
  try {
    const repoPath = path.join(projectDataPath, repo);
    if (fs.existsSync(repoPath)) {
      fs.rmdirSync(repoPath, { recursive: true });
    }

    await gitP.clone(url, repoPath);
  } catch (err) {
    console.error('Error cloning repo: ', err);
  }
});

ipcMain.handle('create-repo', async (event, repo) => {
  try {
    if (!userData) {
      return;
    }
    const url = `https://api.github.com/user/repos`;

    const token = await keytar.getPassword('markin', 'GitHub');
    console.log('Token: ', token);

    const config = {
      headers: {
        Authorization: `token ${token}`
      }
    };
    const data = {
      name: repo,
      private: false
    };

    await axios.post(url, data, config);
  } catch (err) {
    console.error('Error creating repo: ', err);
  }
});

ipcMain.handle('add-repo', async (event, repo) => {
  console.log('Adding repo: ', repo);
  try {
    const repoPath = path.join(projectDataPath, repo);
    if (!fs.existsSync(repoPath)) {
      fs.mkdirSync(repoPath, { recursive: true });
    }

    const gitP = git(repoPath);
    await gitP.init();

    // Check if 'origin' remote exists
    const remotes = await gitP.getRemotes();
    if (remotes.some(remote => remote.name === 'origin')) {
      // If it exists, remove it
      await gitP.removeRemote('origin');
    }

    if (!userData) {
      console.log('No user data found');
      return;
    }

    // Get GitHub account info from userData
    const githubUsername = userData.name;
    const githubRepo = repo;

    // Add remote repository
    await gitP.addRemote('origin', `https://github.com/${githubUsername}/${githubRepo}.git`);
  } catch (err) {
    console.error('Error adding repo: ', err);
  }
});

ipcMain.handle('commit-repo', async (event, repo, message) => {
  try {
    const repoPath = path.join(projectDataPath, repo);
    const gitP = git(repoPath);

    await gitP.add('.');
    await gitP.commit(message);
  } catch (err) {
    console.error('Error committing repo: ', err);
  }
});

ipcMain.handle('push-repo', async (event, repo) => {
  try {
    const repoPath = path.join(projectDataPath, repo);
    const gitP = git(repoPath);

    await gitP.push('origin', 'master');
  } catch (err) {
    console.error('Error pushing repo: ', err);
  }
});

function saveProjectData(projectId: any, data: any) {
  const dirPath = path.join(projectDataPath, projectId);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  const filePath = path.join(dirPath, 'data.json');
  fs.writeFileSync(filePath, JSON.stringify(data));
}

ipcMain.handle('save-project-data', (event, projectId, data) => {
  saveProjectData(projectId, data);
  event.sender.send('folder-operation-completed');
});

function getProjectDataFiles() {
  if (!fs.existsSync(projectDataPath)) {
    return [];
  }

  const folders = fs.readdirSync(projectDataPath).filter(folder => {
    const folderPath = path.join(projectDataPath, folder);
    return fs.statSync(folderPath).isDirectory();
  });

  const files = folders.map(folder => {
    const folderPath = path.join(projectDataPath, folder);
    return {
      folder,
      files: fs.readdirSync(folderPath)
    };
  });

  return files;
}

ipcMain.handle('get-projects-files', async () => {
  const files = getProjectDataFiles();
  return files;
});

ipcMain.handle('get-file', async (event, filePath) => {
  filePath = path.join(__dirname, filePath);
  const data = fs.readFileSync(filePath, 'utf8');
  return data;
});

ipcMain.handle('save-file', (event, filePath, data) => {
  filePath = path.join(__dirname, filePath);
  fs.writeFileSync(filePath, data, 'utf8');
  event.sender.send('file-operation-completed');
});

type ItemDetail = {
  name: string;
  path: string;
  isDirectory: boolean;
  children: ItemDetail[];
};

const getFolderDetails = (folderPath: string): ItemDetail[] => {
  const details: ItemDetail[] = fs.readdirSync(folderPath).map(item => {
    const itemPath = path.join(folderPath, item);
    const isDirectory = fs.statSync(itemPath).isDirectory();

    return {
      name: item,
      path: itemPath,
      isDirectory,
      children: isDirectory ? getFolderDetails(itemPath) : []
    };
  });

  return details;
};

ipcMain.handle('get-project-detail', async (event, folderName) => {
  const folderPath = path.join(projectDataPath, folderName);
  const details = getFolderDetails(folderPath);
  return details;
});

const moveFileOrDirectory = (sourcePath: string, destinationPath: string): void => {
  const absoluteSourcePath = path.resolve(__dirname, sourcePath);
  const absoluteDestinationPath = path.resolve(__dirname, destinationPath);

  try {
    fsExtra.moveSync(absoluteSourcePath, absoluteDestinationPath);
  } catch (error) {
    console.error(`Failed to move file or directory from ${absoluteSourcePath} to ${absoluteDestinationPath}: ${error}`);
  }
};

ipcMain.handle('move-file', async (event, source, destination) => {
  moveFileOrDirectory(source, destination)
  event.sender.send('folder-operation-completed');
})

const createNewFolder = (folderPath: string): void => {
  const absoluteFolderPath = path.resolve(__dirname, folderPath);

  try {
    fs.mkdirSync(absoluteFolderPath);
  } catch (error) {
    console.error(`Failed to create new folder at ${absoluteFolderPath}: ${error}`);
  }
};

ipcMain.handle('create-folder', async (event, folderPath) => {
  createNewFolder(folderPath);
  event.sender.send('folder-operation-completed');
});

// 新しいファイルを作成する関数
const createNewFile = (filePath: string): void => {
  const absoluteFilePath = path.resolve(__dirname, filePath);

  try {
    fs.writeFileSync(absoluteFilePath, '');
  } catch (error) {
    console.error(`Failed to create new file at ${absoluteFilePath}: ${error}`);
  }
};

ipcMain.handle('create-file', async (event, filePath) => {
  createNewFile(filePath);
  event.sender.send('folder-operation-completed');
});


const createWindow = async () => {

  if (BrowserWindow.getAllWindows().length > 0 || mainWindow) {
    return;
  }

  mainWindow = new BrowserWindow({
    width: 1024,
    height: 728,
    frame: false,
    webPreferences: {
      // webpack が出力したプリロードスクリプトを読み込み
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: true,
    },
  });

  // レンダラープロセスをロード
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.on("ready-to-show", () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    if (process.env.START_MINIMIZED) {
      mainWindow.minimize();
    } else {
      mainWindow.show();
    }
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();
};

app.whenReady().then(() => {
  if (BrowserWindow.getAllWindows().length === 0) {
    // アプリの起動イベント発火で BrowserWindow インスタンスを作成
    if (process.defaultApp) {
      if (process.argv.length >= 2) {
        app.setAsDefaultProtocolClient('markin', process.execPath, [path.resolve(process.argv[1])])
      }
    } else {
      app.setAsDefaultProtocolClient('markin')
    }

    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          'Content-Security-Policy': ['script-src \'self\' \'unsafe-inline\' data: \'unsafe-eval\';']
        }
      });
    })

    createWindow();
  }
});

ipcMain.handle('get-user', async (event) => {
  // ユーザーデータを返す
  return userData;
});

ipcMain.handle('logout', async (event) => {
  userData = null;
  if (mainWindow) {
    mainWindow.webContents.send('set-user', null);
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

const server = 'https://update.electronjs.org'
const feed = `${server}/shiki-01/MarkIn/${process.platform}-${process.arch}/${app.getVersion()}`

if (app.isPackaged) { // パッケージされている（ローカル実行ではない）
  autoUpdater.setFeedURL({
    url: feed,
  });
  autoUpdater.checkForUpdates(); // アップデートを確認する

  // アップデートのダウンロードが完了したとき
  autoUpdater.on("update-downloaded", async () => {
    const returnValue = await dialog.showMessageBox({
      message: "アップデートあり",
      detail: "再起動してインストールできます。",
      buttons: ["再起動", "後で"],
    });
    if (returnValue.response === 0) {
      autoUpdater.quitAndInstall();  // アプリを終了してインストール
    }
  });

  // アップデートがあるとき
  autoUpdater.on("update-available", () => {
    dialog.showMessageBox({
      message: "アップデートがあります",
      buttons: ["OK"],
    });
  });

  // アップデートがないとき
  autoUpdater.on("update-not-available", () => {
    dialog.showMessageBox({
      message: "アップデートはありません",
      buttons: ["OK"],
    });
  });

  // エラーが発生したとき
  autoUpdater.on("error", () => {
    dialog.showMessageBox({
      message: "アップデートエラーが起きましたたた",
      buttons: ["OK"],
    });
  });
}